# Generated by Django 3.0.2 on 2020-01-21 06:56

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, unique=True)),
                ('street_name', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)])),
            ],
        ),
    ]
